apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init-job
  namespace: vault
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: vault-admin-sa
      restartPolicy: Never
      containers:
      - name: vault-init
        image: hashicorp/vault:1.14.2
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -euo pipefail
            echo "Running inside cluster. Configuring Vault K8S auth..."
            
            # Use the cluster's internal service address:
            export VAULT_ADDR="http://vault.vault.svc.cluster.local:8200"

            # Enable Kubernetes auth (if not already enabled)
            vault auth enable kubernetes || true
            
            # Configure Kubernetes auth using in-cluster credentials
            vault write auth/kubernetes/config \
              token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
              kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
              kubernetes_host="https://kubernetes.default.svc.cluster.local:443"

            echo "Kubernetes auth config done!"
