# vault-values.yaml
server:
  config: |
    ui = true
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = true
    }
    storage "file" {
      path = "/vault/data"
    }
    seal "gcpckms" {
      project     = "instamini-auto"
      region      = "us-central1"
      key_ring    = "vault-ha-keyring"
      crypto_key  = "vault-auto-unseal"
    }
  # We'll override those "CHANGE_ME_*" from Terraform
  extraEnvironmentVars:
    GOOGLE_APPLICATION_CREDENTIALS: "/etc/vault/key.json"
  volumes:
    - name: gcp-key
      secret:
        secretName: gcp-key
  volumeMounts:
    - name: gcp-key
      mountPath: /etc/vault
      readOnly: true

  # Turn on the Vault Injector for sidecars
  injector:
    enabled: true
