apiVersion: apps/v1
kind: Deployment
metadata:
  name: instamini-mysite
  labels:
    app: instamini
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: instamini
  template:
    metadata:
      labels:
        app: instamini
    spec:
      serviceAccountName: my-app-sa
      containers:
        - name: flask-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo "Starting Flask with MySQL user=$MYSQL_USER pass=$MYSQL_PASS"
              exec python app.py
          env:
            # Using static credentials from mysite-db-secrets
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysite-db-secrets
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysite-db-secrets
                  key: MYSQL_PORT
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: mysite-db-secrets
                  key: MYSQL_DB
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysite-db-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: mysite-db-secrets
                  key: MYSQL_PASS
