apiVersion: v1
kind: Service
metadata:
  name: instamini-mysite
  labels:
    app: instamini
spec:
  type: {{ .Values.service.type }}
  selector:
    app: instamini
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
